import Footer from "@/components/Layout/Footer";
import Navbar from "@/components/Layout/Navbar";
import { Toaster } from "@/components/ui/sonner";
import CreateBlogFAB from "@/features/blogs/CreateBlogFAB";
import getUser from "@/lib/getUser";
import { AuthStoreProvider } from "@/store/AuthStoreProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { FaPlus } from "react-icons/fa";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
      >
        <Navbar user={user} />
        <AuthStoreProvider user={user}>{children}</AuthStoreProvider>
        {user ? (
          <CreateBlogFAB size="small" prefix={<FaPlus />}>
            Create
          </CreateBlogFAB>
        ) : null}
        <Toaster />

        <Footer />
      </body>
    </html>
  );
}
