name: Fullstack CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write
  actions: read
  deployments: write
  id-token: write

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 10.13.1

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      - run: pnpm install

  frontend:
    needs: setup
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.13.1
      - run: pnpm --filter frontend install
      - run: pnpm --filter frontend run lint
      - run: pnpm --filter frontend run test
      - run: pnpm --filter frontend run build

  backend:
    needs: setup
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.13.1

      - run: pnpm --filter backend install
      - run: pnpm --filter backend prisma:gen
      - run: pnpm --filter backend prisma:push
      - run: pnpm --filter backend lint
      - run: pnpm --filter backend run build
