name: Fullstack CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 10.13.1

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install

  frontend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10.13.1
      - run: pnpm install
      - run: pnpm --filter frontend run lint
      - run: pnpm --filter frontend run test
      - run: pnpm --filter frontend run build
      - run: pnpm --filter frontend dlx railway login --token=${{ secrets.RAILWAY_SECRET_KEY }}
      - run: pnpm --filter frontend dlx railway up --service frontend --yes

  backend:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 10.13.1

      - run: pnpm install
      - run: pnpm --filter backend prisma:gen
      - run: pnpm --filter backend prisma:push
      - run: pnpm --filter backend lint
      - run: pnpm --filter backend run build
      - run: pnpm --filter backend dlx railway login --token=${{RAILWAY_SECRET_KEY}}
      - run: pnpm --filter backend dlx railway up --service backend --yes

